spring:
  docker:
    compose:
      enabled: true
      file: 'compose.@activatedProperties@.yaml'
      lifecycle-management: start_and_stop
  datasource:
    url: "jdbc:postgresql://localhost:5432/development"
    username: myuser
    password: mypassword
logging:
  config: 'classpath:log4j2.@activatedProperties@.xml'

