spring:
  docker:
    compose:
      enabled: false
  application:
    name: '${appName}'
  profiles:
    active: '@activatedProperties@'
    default: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1         # Connections always available
      idle-timeout: 20000
      max-lifetime: 60000
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      format_sql: true
      show_sql: false
    open-in-view: false
  jackson:
    serialization:
      indent-output: true
  messages:
    encoding: UTF-8
server:
  servlet:
    context-path: '/api'
    encoding:
      charset: UTF-8
project:
  security:
    jwt:
      expirationInMilliseconds: 43200000     # 1000 ms * 60 s * 60 m * 12 h
