spring:
  docker:
    compose:
      enabled: true
      file: 'compose.@activatedProperties@.yaml'
      lifecycle-management: start_and_stop
  datasource:
    url: "jdbc:postgresql://localhost:5432/development"
    username: myuser
    password: mypassword
  jpa:
    # Debugging N+1 QUERIES problem
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
logging:
  config: 'classpath:log4j2.@activatedProperties@.xml'

