spring:
  docker:
    compose:
      enabled: false
  application:
    name: '${appName}'
  profiles:
    active: '@activatedProperties@'
    default: dev
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5         # Connections always available
      idle-timeout: 30000
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  jackson:
    serialization:
      indent-output: true
server:
  servlet:
    context-path: '/api'
    encoding:
      charset: UTF-8
project:
  security:
    jwt:
      expirationInMilliseconds: 2592000000     # 1000 ms * 60 s * 60 m * 24 h * 30 d
