name: ${appName}-dev-stack

networks:
  ${appName}-postgres-dev-network:
    driver: bridge

volumes:
  ${appName}-postgres-dev-volume:
    driver: local

services:
  ${appName}-dev-db:
    image: 'postgres:17-alpine'
    container_name: '${appName}-dev-database'
    env_file:
      - path: .docker.dev.env
        required: true
    networks:
      - ${appName}-postgres-dev-network
    ports:
      - 5432:5432
    volumes:
      - ./src/main/sql/01-user-schema.sql:/docker-entrypoint-initdb.d/01-user-schema.sql
