name: ${appName}-stack

services:
  dev-db:
    image: 'postgres:17-alpine'
    container_name: 'Development-database'
    environment:
      - 'POSTGRES_DB=development'
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=mypassword'
    ports:
      - '5432:5432'
    volumes:
      - ./src/main/sql/user-schema.sql:/docker-entrypoint-initdb.d/1-user-schema.sql

  dev-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: 'Development-elasticsearch'
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - dev-elasticsearch

networks:
  elastic:
    driver: bridge

volumes:
  esdata:
    driver: local