name: ${appName}-stack

services:
  db-dev:
    image: 'postgres:17-alpine'
    container_name: 'Dev-container'
    environment:
      - 'POSTGRES_DB=development'
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=mypassword'
    ports:
      - '5432:5432'
    volumes:
      - ./src/main/sql/user-schema.sql:/docker-entrypoint-initdb.d/1-user-schema.sql
