name: ${appName}-stack

services:
  db-test:
    image: 'postgres:17-alpine'
    container_name: 'Test-container'
    environment:
      - 'POSTGRES_DB=testing'
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=mypassword'
    ports:
      - '5431:5432'
    volumes:
      - ./src/main/sql/user-schema.sql:/docker-entrypoint-initdb.d/1-user-schema.sql
