name: ${appName}-stack

networks:
  ${appName}-postgres-network:
    driver: bridge

volumes:
  ${appName}-postgres-volume:
    driver: local

services:
  development-database:
    image: 'postgres:17-alpine'
    container_name: 'Development-database'
    env_file:
      - path: .docker.dev.env
        required: true
    environment:
      - POSTGRES_DB: ${POSTGRES_DB}
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./src/main/sql/user-schema.sql:/docker-entrypoint-initdb.d/1-user-schema.sql
